feat: Docker 배포를 위한 SSH 배포 단계 추가 및 워크플로우 수정

diff --git a/.github/workflows/push-docker.yaml b/.github/workflows/push-docker.yaml
--- a/.github/workflows/push-docker.yaml
+++ b/.github/workflows/push-docker.yaml
@@ -6,7 +6,7 @@ on:
     branches: [main]
 
 jobs:
-  docker:
+  build-and-push:
     runs-on: ubuntu-latest
 
     steps:
@@ -32,3 +32,34 @@ jobs:
           push: true
           # 리포지토리 이름을 태그로 사용
           tags: ${{ vars.DOCKERHUB_USERNAME }}/next-docker-githubaction:latest
+
+  deploy:
+    name: Deploy to Server
+    runs-on: ubuntu-latest
+    needs: build-and-push
+
+    steps:
+      - name: Deploy via SSH
+        uses: appleboy/ssh-action@v1.2.0
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            sudo apt-get update && sudo apt upgrade -y
+            if ! command -v docker &> /dev/null;
+            then
+              echo "Docker not found, installing Docker..."
+              sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
+              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" -y
+              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+              sudo apt install docker-ce -y
+              sudo apt update
+              sudo systemctl enable docker
+              sudo systemctl start docker
+            fi
+            docker pull ${{ vars.DOCKERHUB_USERNAME }}/next-docker-githubaction:latest
+            docker stop next-docker-githubaction || true
+            docker rm next-docker-githubaction || true
+            docker run -d -p 80:3000 --name next-docker-githubaction ${{ vars.DOCKERHUB_USERNAME }}/next-docker-githubaction:latest
